### ISSUE TITLE
What is private.js

### ISSUE THREAD

**Issue by ajkachnic** [SnowLord7/Gimkit-Hack#7]
From what I can tell, `private.js` runs AES encrypted JavaScript code, in a password protected manner. It also includes the source code for CryptoJS to do this operation. However, what is the purpose of this and why is it included in this repo?

I assume it has something to do with GimKit, but I'm still curious as to why it's here. What is it used for here?

**Comment by SnowLord7** [comment]
In order to prevent Gimkit from constantly updating and implementing more anti-cheat features I decided to make the updated Gimkit script password protected to prevent Gimkit developers from easily viewing how the cheat works. I am currently only giving away access to the password through request.

In a couple days I will be releasing a * hopefully groundbreaking* extension which should solve all current and future issues.

**Comment by ajkachnic** [comment]
Okay thank you for clarifying

**Comment by Knocker379** [comment]
Can I get the password?

**Comment by Knocker379** [comment]
I'm new to GitHub so I don't understand much. Is there a way you can private message the code to me?

**Comment by SnowLord7** [comment]
I don't think I know of any way to PM a user on github. I'll be releasing an extension soon for Gimkit that will be publically available.

**Comment by FloppyT** [comment]
I'd be interested to see how powerful it is. Good luck on it
